STRINGS = {
    :pleaseenteraletter         => "Please enter a letter: ",
    :inputisnotlowercase        => "Input is not lower case",
    :inputhasalreadybeenguessed => "Input has already been guessed",
    :inputisinvalid             => "Input is invalid",
    :gameover                   => "GAME OVER!",
    :youwon                     => "You won!",
    :youlost                    => "You lost!",
    :youhavelivesleft           => "You have :lives lives left",
    :youhadlivesleft            => "You had :lives lives left",
    :currentguessis             => "Current guess is: :guess",
    :finalguesswas              => "Final guess was: :guess",
    :youhaveguessed             => "You have guessed: :guesses",
    :youhadguessed              => "You had guessed: :guesses",
}
