STRINGS = {
    :pleaseenteraletter         => "Por favor, introduzca una letra: ",
    :inputisnotlowercase        => "La entrada no es minúscula",
    :inputhasalreadybeenguessed => "De entrada ya se ha conjecturado",
    :inputisinvalid             => "Entrada no es valida",
    :gameover                   => "¡JUEGA TERMINADO!",
    :youwon                     => "¡Ganaste!",
    :youlost                    => "¡Perdiste!",
    :youhavelivesleft           => "Usted tiene :lives vidas izquierda",
    :youhadlivesleft            => "Usted tenía :lives vidas izquierda",
    :currentguessis             => "Conjectura actual es: :guess",
    :finalguesswas              => "Conjectura final fue: :guess",
    :youhaveguessed             => "Usted tiene adivinado: :guesses",
    :youhadguessed              => "Usted ha adivinado: :guesses",
}
