STRINGS = {
    :pleaseenteraletter         => "S'il vous plaît entrer une lettre: ",
    :inputisnotlowercase        => "Entrée ne sont pas minuscules",
    :inputhasalreadybeenguessed => "Entrée a déjà été deviné",
    :inputisinvalid             => "Entrée est invalide",
    :gameover                   => "JEU TERMINÉ!",
    :youwon                     => "Vous avez gagné!",
    :youlost                    => "Vous avez perdu!",
    :youhavelivesleft           => "Vous avez :lives vies gauche",
    :youhadlivesleft            => "Vous aviez :lives vies gauche",
    :currentguessis             => "Conjecture actualle est: :guess",
    :finalguesswas              => "Conjecture finale était: :guess",
    :youhaveguessed             => "Vous avez deviné: :guesses",
    :youhadguessed              => "Vous aviez deviné: :guesses",
}
